-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguwgc7ybfM7ewvWZf
A6uttYdyFYpfuA8dQZij9GNXYOSgCgYIKoZIzj0DAQehRANCAAR9U8PFdmyL4EQA
ppZ5GOpy2oMIWBcTP3FljFv3CpCtcZl0RuqIvFhlWV8T+iIftoJOb4sSnZ2zUIYC
wN5xbTJT
-----END PRIVATE KEY-----