// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofIy7LN_X8vm13QfouvSzxxBo4sqSKOk',
    appId: '1:425131648806:web:1145939548cd848d7f43e7',
    messagingSenderId: '425131648806',
    projectId: 'bookplayzadmin-2e925',
    authDomain: 'bookplayzadmin-2e925.firebaseapp.com',
    storageBucket: 'bookplayzadmin-2e925.firebasestorage.app',
    measurementId: 'G-9PKB45L8F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz7pRearrpq0QBS2S9FfcSgqwFuLwWF2c',
    appId: '1:425131648806:android:7e58417ac9051fe87f43e7',
    messagingSenderId: '425131648806',
    projectId: 'bookplayzadmin-2e925',
    storageBucket: 'bookplayzadmin-2e925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCql01L2Ja4PLRoLfrUm_JP9-Yfi2feq7M',
    appId: '1:425131648806:ios:7386a90a013e841b7f43e7',
    messagingSenderId: '425131648806',
    projectId: 'bookplayzadmin-2e925',
    storageBucket: 'bookplayzadmin-2e925.firebasestorage.app',
    iosBundleId: 'com.bookplayz.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCql01L2Ja4PLRoLfrUm_JP9-Yfi2feq7M',
    appId: '1:425131648806:ios:06b12e4158c70bc17f43e7',
    messagingSenderId: '425131648806',
    projectId: 'bookplayzadmin-2e925',
    storageBucket: 'bookplayzadmin-2e925.firebasestorage.app',
    iosBundleId: 'com.example.bookplayz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCofIy7LN_X8vm13QfouvSzxxBo4sqSKOk',
    appId: '1:425131648806:web:1145939548cd848d7f43e7',
    messagingSenderId: '425131648806',
    projectId: 'bookplayzadmin-2e925',
    authDomain: 'bookplayzadmin-2e925.firebaseapp.com',
    storageBucket: 'bookplayzadmin-2e925.firebasestorage.app',
    measurementId: 'G-9PKB45L8F7',
  );
}
